### ISSUE TITLE
using widget on master-detail page

### ISSUE THREAD

**Issue by markvwd** [AuraQ/AutoCompleteForMendix#10]
I'm having issues implementing this widget on a master-detail page (the widget being used in the detail part of the page). With the widget on the page the page doesn't load, only displays the loader, without the widget it load without any problems.

I'm not sure where to look for the solution, could this be a known issue with the widget or a problem with mendix?

**Comment by lindski** [comment]
This was an issue with the widget... when the obj is null (e.g. the initial state of the 'detail' dataview) it wasn't executing the callback so the page didn't load correctly. Added the callback and a master detail test page to the test project. 

Fixed in commit fee00ae

Will be added to the next release. In the meantime, you can use the mpk from the dist folder

**Comment by markvwd** [comment]
@lindski  thanks for the updates and fixes. I'll be back at work on monday to implement the new version
