### ISSUE TITLE
Request: add constrained by possibility

### ISSUE THREAD

**Issue by dkho87** [AuraQ/AutoCompleteForMendix#14]
Hi,
I don't know how much work it would be, but currently you have the possibility to add an XPath constraint, which is already great!

However, sometimes you want to use a Constrained by (as seen on the default Mendix reference selector) functionality which has the bonus of being able to apply constraints with changes in memory. 

My use case is the following:

Project 1 <-- \* Subproject 1 <-- \* Activity

What I would like to achieve is that if a Project is selected, the selector for Subproject gets constrained, without having to do a commit first (as that could be handled with the XPath constraint).

Of course, you could use default Mendix functionality, but what I'm looking for is exactly the functionality this widget already offers.

**Comment by lindski** [comment]
It is possible to set constrained by using [%CurrentObject] however there is a limitation in that the association needs to be set and committed on the context object. 

I've added a test called 'Constrained By' in the test project that shows using [%CurrentObject] but I will need to have a think to see how we can achieve the same behaviour with associations set in memory (which is what is really needed)

**Comment by lindski** [comment]
Ok, I think I have managed to do this by adding two additional parameters in the Search tab:

1. Constrained by [Context] - Select an association from the data view context if you want the results to be constrained by a particular object. Must be used alongside 'Constrained by [Source]'
2. Constrained by [Source] - Select an association from the AutoComplete's source entity if you want the results to be constrained by a particular object. Must be used alongside 'Constrained by [Context]'

I need the first one in order to retrieve the ID of the object to filter the results by. I need the second one so I can apply the correct xpath with the retrieved ID.

An updated widget is available in the dist folder. Let me know if this solves it for you

**Comment by lindski** [comment]
sorry, dist folder is only on my local machine! You'll need to take the widget from the widgets folder in the test project

**Comment by dkho87** [comment]
I'm testing it right now, but at first sight it seems to do exactly that what I was looking for, so KUDOS and much appreciation for working on this! I'll do some test (On change, etc.) and come back to you to finalize this.

**Comment by lindski** [comment]
Great, let me know how your testing goes... if all goes well I'll publish a new release on to the app store

**Comment by dkho87** [comment]
Does exactly what I need! Only thing I'll take care of with an On Change microflow is emptying certain associations as soon as something up the tree requires it (for example: Category was Food with subcategory Drinks and category is changed to Cars. Subcategory remains selected at Drinks, while the possible options is now different. But like I said, nothing that can't be handled through On Change microflow logic)
