### ISSUE TITLE
Previous search results overwrite last search results

### ISSUE THREAD

**Issue by emagiz** [AuraQ/AutoCompleteForMendix#17]
Hi,

Thanks for making this widget, we've started using it but found an issue which I will try to describe below:

I’ve noticed that if you start typing to search and the minimum number of characters before the search is executed is entered, the widget will start searching.
But when typing some more characters a new search action is triggered, this search action is completed earlier then the first search action.
The result on screen is that you first see the results of the second search action, but these results will be overwritten by the first search action (see the attached screenshot). So the results don’t match the input characters anymore.

I also added a screenshot which shows the result of the behavior described above.

![autocompleteformendix](https://cloud.githubusercontent.com/assets/18661579/19593809/9ed5db4e-9782-11e6-8b6b-46d39f320f68.JPG)

**Comment by lindski** [comment]
Apologies for the delay in picking this up

I've made a slight change to the widget (included in commit a3b4269) that checks the current search term before processing the results of the XPath query. If the search term is the same as the one used in the XPath it processes the results, otherwise it doesn't do anything.

An updated widget is available in the widgets folder in the test project. Let me know if this solves it for you

**Comment by emagiz** [comment]
No apologies necessary, we thank you a lot for the fix! We updated the component and we did not see the issue anymore, thanks.
