### ISSUE TITLE
Widget Nonresponsive when opened in Popup layouts in Mendix 7.10

### ISSUE THREAD

**Issue by mkumpf** [AuraQ/AutoCompleteForMendix#32]
Recently converted a project to 7.10.  The widget is non responsive when it is used on popup pages in 7.10 - worked fine in 7.9.  If I change the page template to responsive (top bar), the widget works fine again.

**Comment by lindski** [comment]
This will be added in the next release. The widget in the test project includes an extra property (Parent Selector) to support this if you want to take a look however the final build of version 4 will be a bit different as I'm aiming to add some more fixes over the next couple of weeks.

The issue was caused by the dropdown getting rendered on the main page which is not accessible with a pop up open... the new property allows you to render it correctly in the right place.

**Comment by lindski** [comment]
This has now been fixed and is included in v4 of the widget, available in the app store.

New property available Parent Selector which takes an optional css3 selector... in a modal popup set a value of .modal-dialog for the widget to work
