### ISSUE TITLE
Feature request: Make the widget role/security aware to set it read-only or editable

### ISSUE THREAD

**Issue by kmn0** [AuraQ/AutoCompleteForMendix#55]
Hi there. Is it much work to make the widget behave like other Mendix widgets and act on the security settings to make the widget read-only or editable, based on the role security settings in the entity/attribute. I believe in other Mendix widgets this is called Editability Default:
Default (default) The value is editable if security allows it (as in, if the user that is signed in has write access to the selected attribute).
This would really help us in our project. 
If this would be possible/viable then we would, of course be willing to contribute to the solution.
Thanks and regards,
Gerrit van Kammen
btw I read that you have worked together with Phil Waterhouse (Springer Healthcare) on the SMART app. Phil is a colleague of mine, although we have never worked together on a project.

**Comment by lindski** [comment]
Hi there. 

I believe this is possible, although I would need to take a closer look. There are a few other outstanding issues that I need to look at as well which hasn't been possible recently due to other work commitments so I could bundle all of them in together in a new release at some point over the next few weeks.

Do you have a particular timescale you need this by?

Yes, I know Phil really well! Worked on the first release of SMART with him and have done bits and bobs up in Chester over the years with the team up there.

Cheers

Iain

**Comment by kmn0** [comment]
Hi Iain, good to know that this is feasible! As far as the timeline, we need to go live early June and we are now in the development / uat phase, working in 2-weekly sprints. Currently we are implementing the workaround for every usage of the widget  (now 30 times and wip) to create a calculated attribute and use that attribute in the disabled via attribute property of the widget. In the microflow of the calculated attribute, we check the roles of the logged in user and set a boolean true or false. This works, but is not optimal. We could stop this once we know we can expect the new feature before June, add some uat time, then we are looking at mid May 2020.
Will say hi to Phil on our slack channel!

**Comment by lindski** [comment]
If the user does not have write access to the association, the dropdown will be rendered in a disabled state.

This is now part of v6.0.0, available in the app store
