### ISSUE TITLE
Autocomplete not working in Mendix 8.12.1

### ISSUE THREAD

**Issue by Alain1970** [AuraQ/AutoCompleteForMendix#59]
I have upgraded my project from Mendix 8.8.1 to Mendix 8.12.1 and as a result of that upgrade, the autocomplete widget no longer works. Apparantly the current version does not work in Mendix 8.12.1; it only shows the message: 'No results found.'

We are currently in the process of handling the last customer feedback before deploying our new application on production, but cannot do this because of this issue with the autocomplete widget. I hope you have time to look into this issue and will be able to solve it.

**Comment by bpanne** [comment]
Same problem here. Upgrade from 8.7 to 8.12.1 and it is not working anymore. Worked fluently before. Also tried 8.13.0 today, not working as well

**Comment by lindski** [comment]
Looks like the 'amount' parameter on mx.data.get has changed slightly. A 0 value is now treated as no results, rather than all results

I will fix the default in the next version but, for now, you just need to change the Max Records property in 'Search - XPath' to -1 and it will behave the same as before

**Comment by pratleymatthew** [comment]
This issue has been fixed in v6.1.0, now available in the Mendix marketplace.
